/*
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.

Example:
Input:
s = "abcd"
t = "abcde"
Output:
e
Explanation:
'e' is the letter that was added.
*/
#include <iostream>
#include <vector>

using namespace std;

class Solution {
    public:
        char findTheDifference(string s, string t) {
            vector<int> m(26, 0);
            for(int i = 0; i < s.length(); i++) {
                ++m[s[i] - 'a'];
            }
            for(int i = 0; i < t.length(); i++) {
                if(--m[t[i] - 'a'] < 0) return t[i];
            }
            return NULL;
        }

        // a ^ a = 0
        char findTheDifference_Bit(string s, string t) {
            char res = 0;
            for(char ss : s) res ^= ss;
            for(char tt : t) res ^= tt;
            return res;
        }
};

int main() {
    Solution sol;
    return 0;
}

/*


*/